### ISSUE TITLE
Better card "border"

### ISSUE THREAD

**Issue by omar2205** [CodingGarden/sproutkit#22]
```css
.something {
  --border-color: red;
  box-shadow: inset 20px 0px 0px 0px var(--border-color), 20px 0px var(--border-color);
}
```

will work
![image](https://user-images.githubusercontent.com/1373867/203421864-9224fd3f-0ec0-4694-a127-6bb5ec156883.png)
